Repository Lightning-Universe/CVPR22-MAE_research-poster, pull requests merged in 2023-02, with the labels that each got.

#19 Add dependabot PR approver
  .github/ci-approve-dependabot-pr
Labels: ci / tests

#20 Update README.md
  README.md
Labels: documentation

#21 Add LICENSE
  LICENSE
  fb_mae/__init__.py
  fb_mae/util/__init__.py
  tests/test_app_gallery.py
  tests/test_research_app.py
Labels: documentation

#22 Add some CI
  .github/workflows/ci-checks.yml
Labels: ci / tests

#26 drop pkg related files
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/ci-approve-dependabot-pr.yml
  .github/workflows/ci-checks.yml
  .github/workflows/ci-testing.yml
  .github/workflows/install_test.yml
  .gitmodules
  .lightningignore
  LICENSE
  Makefile
  app.py
  assets/demo.png
  assets/use-template.png
  mae_poster/__init__.py
  mae_poster/demo.py
  mae_poster/models.py
  mae_poster/util/__init__.py
  mae_poster/util/crop.py
  mae_poster/util/datasets.py
  mae_poster/util/lars.py
  mae_poster/util/lr_decay.py
  mae_poster/util/lr_sched.py
  mae_poster/util/misc.py
  mae_poster/util/pos_embed.py
  requirements.txt
  research_app/__about__.py
  research_app/__init__.py
  research_app/components/__init__.py
  research_app/components/app_status.py
  research_app/components/jupyter_lite.py
  research_app/components/jupyter_notebook.py
  research_app/components/model_demo.py
  research_app/setup_tools.py
  research_app/utils.py
  setup.py
  tests/__init__.py
  tests/test_app_gallery.py
Labels: enhancement
